cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #24273a
selection_background  #c6a0f6
url_color             #b7bdf8

color0   #1e2030
color1   #ff7295
color2   #7cf891
color3   #ffd872
color4   #a1a8eb
color5   #3b4072
color6   #b7bdf8
color7   #eff1ff
color8   #9596a1
color9   #ff9fb7
color10  #a5ffb5
color11  #ffe6a5
color12  #c6cbff
color13  #d0d4ff
color14  #e0e3ff
color15  #f8f9ff
