command_line_placement = "bottom"
error_display_mode = "pane"
highlight_duration_ms = 250
debounce_duration_ms = 500

[theme.cmd_regular]

[theme.cmd_regular_pipe]
fg = "green"

[theme.cmd_regular_current]

[theme.cmd_highlight]
fg = "black"
bg = "yellow"

[theme.cmd_highlight_pipe]
bg = "yellow"

[theme.cmd_highlight_current]
fg = "black"
bg = "yellow"

[theme.cmd_quoted]
fg = "yellow"

[theme.cmd_invalid]

[theme.output_highlight]
fg = "white"
bg = "magenta"

[theme.output_highlight_current]
fg = "black"
bg = "yellow"

[theme.line_nums]
fg = "magenta"

[keybindings]
quit = ["ctrl+c"]
execute_full = ["enter"]
execute_until_current = ['alt+\']
execute_until_prev = ["alt+|"]
reset_input = ["alt+i"]
scroll_down = [
    "down",
    "alt+j",
]
scroll_down_page = [
    "pagedown",
    "ctrl+d",
    "alt+down",
]
scroll_up = [
    "up",
    "alt+k",
]
scroll_up_page = [
    "pageup",
    "ctrl+u",
    "alt+up",
]
scroll_left = ["alt+h"]
scroll_right = ["alt+l"]
toggle_wrap = ["alt+w"]
history_prev = ["ctrl+p"]
history_next = ["ctrl+n"]
subcommand_next = ["alt+right"]
subcommand_prev = ["alt+left"]
complete = ["tab"]
complete_prev = [
    "shift+tab",
    "shift+backtab",
    "alt+tab",
    "backtab",
]
